import { TextProperties } from "@/components/editor/nodes/base-node";

export interface DiagramComponent {
  groupName: string;
  name: string;
  iconName: string;
  type: string;
  prefix?: string; // New property
  backgroundColor?: string;
  showFrame?: boolean; // Show frame around the node - default: true
  sku?: string[];
  sizeOptions?: {
    name: string;
    options: string[];
  }[];
  otherOptions?: {
    name: string;
    options: string[];
  }[];
  defaultTextProperties?: TextProperties;
}

export const ResourceNodeTypes: DiagramComponent[] = [
  {
    groupName: "Shapes",
    name: "Rectangle",
    iconName: "Rectangle",
    type: "rectangleShape",
    defaultTextProperties: { textAlign: "center", verticalAlign: "middle" },
  },
  {
    groupName: "Shapes",
    name: "Circle",
    iconName: "Circle",
    type: "circleShape",
    defaultTextProperties: { verticalAlign: "middle" },
  },
  {
    groupName: "Shapes",
    name: "Users",
    iconName: "Users",
    type: "usersShape",
    defaultTextProperties: { verticalAlign: "middle" },
  },
  {
    groupName: "Shapes",
    name: "Email",
    iconName: "Email",
    type: "emailShape",
    defaultTextProperties: { verticalAlign: "middle" },
  },
  {
    groupName: "Shapes",
    name: "Phone",
    iconName: "Phone",
    type: "phoneShape",
    defaultTextProperties: { verticalAlign: "middle" },
  },
  {
    groupName: "Shapes",
    name: "Document",
    iconName: "Document",
    type: "documentShape",
    defaultTextProperties: { verticalAlign: "middle" },
  },
  {
    groupName: "Annotations",
    name: "Text",
    iconName: "Text",
    type: "textShape",
    defaultTextProperties: { textAlign: "center", verticalAlign: "middle" },
  },
  {
    groupName: "Annotations",
    name: "Note",
    iconName: "Note",
    type: "noteShape",
    defaultTextProperties: { textAlign: "center", verticalAlign: "middle" },
  },
  {
    groupName: "Annotations",
    name: "Comment",
    iconName: "Comment",
    type: "commentShape",
    defaultTextProperties: { textAlign: "center", verticalAlign: "middle" },
  },
  {
    groupName: "General",
    name: "Subscription",
    iconName: "Subscriptions",
    type: "azureResourceCollection",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "General",
    name: "Resource Group",
    iconName: "ResourceGroups",
    type: "azureResourceCollection",
    prefix: "rg-",
    backgroundColor: "bg-collectionNodes-background100",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "General",
    name: "Management Group",
    iconName: "ManagementGroups",
    type: "azureResourceCollection",
    backgroundColor: "bg-collectionNodes-background100",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Networking",
    name: "Virtual Network",
    iconName: "VirtualNetworks",
    type: "azureResourceCollection",
    prefix: "vnet-",
    backgroundColor: "bg-collectionNodes-background200",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Networking",
    name: "Subnet",
    iconName: "Subnet",
    type: "azureResourceCollection",
    prefix: "snet-",
    backgroundColor: "bg-collectionNodes-background300",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Networking",
    name: "Load Balancer",
    iconName: "LoadBalancers",
    type: "azureResource",
    prefix: "lb-",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Networking",
    name: "Application Gateway",
    iconName: "ApplicationGateways",
    type: "azureResource",
    prefix: "agw-",
    sku: ["Basic", "Standard V2", "WAF V2"],
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Networking",
    name: "Public IP Address",
    iconName: "PublicIPAddresses",
    type: "azureResource",
    prefix: "pip-",
    showFrame: false,
    sku: ["Standard", "Basic"],
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
    otherOptions: [
      {
        name: "IP Version",
        options: ["IPv4", "IPv6"],
      },
      {
        name: "Tier",
        options: ["Regional", "Global"],
      },
      {
        name: "Availability zone",
        options: ["Zone-redundant", "No Zone", "1", "2", "3"],
      },
    ],
  },
  {
    groupName: "Networking",
    name: "NAT Gateway",
    iconName: "NAT",
    type: "azureResource",
    prefix: "ng-",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
    otherOptions: [
      {
        name: "Availability zone",
        options: ["No Zone", "1", "2", "3"],
      },
    ],
  },
  {
    groupName: "Networking",
    name: "Front Door",
    iconName: "FrontDoorAndCDNProfiles",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Networking",
    name: "Virtual Network Gateway",
    iconName: "VirtualNetworkGateways",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Compute",
    name: "Virtual Machine",
    iconName: "VirtualMachine",
    type: "azureResource",
    prefix: "vm-",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Compute",
    name: "App Service",
    iconName: "AppServices",
    type: "azureResource",
    prefix: "app-",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Compute",
    name: "App Service Plan",
    iconName: "AppServicePlans",
    type: "azureResource",
    sku: [
      "B1 Free",
      "B2 Basic",
      "B3 Basic",
      "S1 Standard",
      "S2 Standard",
      "S3 Standard",
      "P1 PremiumV2",
      "P2 PremiumV2",
      "P3 PremiumV2",
      "P1v3 PremiumV3",
      "P2v3 PremiumV3",
      "P3v3 PremiumV3",
      "Y1 Shared",
      "F1 Free",
      "I1 Isolated",
      "I2 Isolated",
      "I3 Isolated",
    ],
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Compute",
    name: "Function App",
    iconName: "FunctionApps",
    type: "azureResource",
    prefix: "func-",
    sku: [
      "Flex Consumption",
      "Consumption",
      "Functions Premium",
      "App Service",
      "Container Apps environment",
    ],
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Compute",
    name: "Container Instance",
    iconName: "ContainerInstances",
    type: "azureResource",
    sku: ["Standard", "Confidential (development policy)"],
    sizeOptions: [
      {
        name: "CPU",
        options: ["1", "2", "4"],
      },
      {
        name: "Memory",
        options: ["1", "2", "4", "8", "16"],
      },
      {
        name: "GPU",
        options: ["None", "V100"],
      },
    ],
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Compute",
    name: "Container Apps",
    iconName: "ContainerInstances",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Databases",
    name: "SQL Server",
    iconName: "SQLServer",
    type: "azureResourceCollection",
    prefix: "sql-",
    backgroundColor: "bg-collectionNodes-background200",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Databases",
    name: "SQL Database",
    iconName: "SQLDatabase",
    type: "azureResource",
    prefix: "sqldb-",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
    otherOptions: [
      {
        name: "Backup storage redundancy",
        options: [
          "Locally-redundant",
          "Zone-redundant",
          "Geo-redundant",
          "Geo-Zone-redundant",
        ],
      },
    ],
  },
  {
    groupName: "Databases",
    name: "Cosmos DB",
    iconName: "AzureCosmosDB",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Databases",
    name: "Azure Database for MySQL",
    iconName: "AzureDatabaseMySQLServer",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Databases",
    name: "Azure Database for PostgreSQL",
    iconName: "AzureDatabasePostgreSQLServer",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Databases",
    name: "Cache for Redis",
    iconName: "CacheRedis",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Identity",
    name: "App Registration",
    iconName: "AppRegistrations",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Identity",
    name: "Managed Identity",
    iconName: "ManagedIdentities",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Identity",
    name: "User Group",
    iconName: "UserGroups",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Identity",
    name: "User",
    iconName: "Users",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Identity",
    name: "Azure AD B2C",
    iconName: "AzureADB2C",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Monitoring",
    name: "Log Analytics Workspace",
    iconName: "LogAnalyticsWorkspaces",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Monitoring",
    name: "Application Insights",
    iconName: "ApplicationInsights",
    prefix: "appi-",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Monitoring",
    name: "Azure Monitor",
    iconName: "Monitor",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Security",
    name: "Key Vault",
    iconName: "KeyVaults",
    prefix: "kv-",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Storage",
    name: "Storage Account",
    iconName: "StorageAccounts",
    type: "azureResource",
    prefix: "st",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
    otherOptions: [
      {
        name: "Type",
        options: [
          "Standard v2",
          "Premium block blobs",
          "Premium file shares",
          "Premium page blobs",
        ],
      },
      {
        name: "Redundancy",
        options: [
          "Locally-redundant storage (LRS)",
          "Zone-redundant storage (ZRS)",
          "Geo-redundant storage (GRS)",
          "Geo-Zone-redundant storage (GZRS)",
        ],
      },
    ],
  },
  {
    groupName: "Storage",
    name: "Blob Storage",
    iconName: "BlobBlock",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Storage",
    name: "File Storage",
    iconName: "File",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Storage",
    name: "Queue Storage",
    iconName: "StorageQueue",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Storage",
    name: "Table Storage",
    iconName: "TableStorage",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Storage",
    name: "Backup Vault",
    iconName: "BackupVault",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "Web",
    name: "Static Web App",
    iconName: "StaticApps",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
    otherOptions: [
      {
        name: "Hosting Plan",
        options: ["Free", "Standard", "Dedicated"],
      },
    ],
  },
  {
    groupName: "DevOps",
    name: "Azure DevOps",
    iconName: "AzureDevOps",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "DevOps",
    name: "Backlog",
    iconName: "Backlog",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "DevOps",
    name: "Code",
    iconName: "Code",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
  {
    groupName: "DevOps",
    name: "Managed DevOps Pool",
    iconName: "ManagedDevOpsPools",
    type: "azureResource",
    defaultTextProperties: { textAlign: "left", verticalAlign: "middle" },
  },
];
